name: CI

on: [ push, pull_request ]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        otp: [ '24.2']
        elixir: [ '1.13' ]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 25.0
            elixir: 1.13
            coverage: true
          - otp: 24.0
            elixir: 1.12
            coverage: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test --trace
