name: CI

on: [ push, pull_request ]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0
          elixir-version: 1.13

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

  test:
    name: Test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [ '24.0', '25.0' ]
        elixir: [ '1.9', '1.12.3', '1.13.0' ]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test --trace
